### ISSUE TITLE
Selections only working in initially visible tab/accordion containers

### ISSUE THREAD

**Issue by mgrabmann** [bqplot/bqplot#1180]
I have a similar problem to the one reported in [#1085 ](https://github.com/bqplot/bqplot/issues/1085). 
The fix from there doesn't seem to work in all cases.

Here is an example:

```
import bqplot as bq
import numpy as np
from ipywidgets import *
from bqplot import pyplot as plt 

class HistTest():
    def __init__(self):
        self.scale_x = LinearScale()
        self.scale_y = LinearScale()
        self.hist_tmp = plt.hist(
            np.random.randn(100),
            scales={'sample': self.scale_x, 'count': self.scale_y},
        )
        self.sel_range = bq.interacts.BrushIntervalSelector(
            scale=self.scale_x,
        )
        self.fig_hist = bq.Figure(
            marks=[self.hist_tmp],
            interaction=self.sel_range
        )
            
    def show(self):
        return self.fig_hist
    
fig1 = HistTest()
fig2 = HistTest()
tabs = widgets.Tab(children=[fig1.show(), fig2.show()])
tabs.selected_index=0
tabs.set_title(0,'Selector works')
tabs.set_title(1,"Selector doesn't work")
tabs
```

**Comment by ChakriCherukuri** [comment]
Like plotly and dashboards from other plotting liraries, bqplot should not be limited to the narrow output cells of notebooks. Using voila we can show the bqplot dashboards on full screen. Some of the examples I added are meant for that purpose.

**Comment by samwelborn** [comment]
This is happening in my app using `Accordion`s.

I mentioned an issue [here](https://github.com/glue-viz/bqplot-image-gl/issues/79) about a figure not showing up immediately, and me having to resize my screen to see it.

I demonstrate this in the following 3 videos, along with the selectors not working when in accordions when they are not initially selected as mentioned above.

The first time I create the image viewer app that I made, it is already in an open accordion. While I have to resize my screen to see it, it still functions as desired:
![1](https://user-images.githubusercontent.com/55868530/151507796-4cb84b57-6420-48c3-82cd-7e03c30b6b50.gif)

This only happens with initially unopened accordions/tabs, as you can see here. I have referenced this image viewer in another section of my app and intentionally set `selected_index=0`:
![2](https://user-images.githubusercontent.com/55868530/151507939-776b3b47-ddb2-48f9-b85c-2d5c51a4692e.gif)

Finally, I changed `selected_index=None` when instantiating the `Accordion`. This causes the following behavior:
![3](https://user-images.githubusercontent.com/55868530/151508043-ab490e7e-cf39-4032-9286-053fabcf6b69.gif)

Where the selector no longer works. When this is happening, it is sending the following to my callback:
![image](https://user-images.githubusercontent.com/55868530/151509172-21aa73eb-a5e8-4a36-9474-7041d730e739.png)

where typically it should look more like this:
![image](https://user-images.githubusercontent.com/55868530/151509236-777b481a-d72c-40f0-bac9-28b36ab37331.png)

I'm not sure if the zoom/selector issues are related. I am using the beta release of ipywidgets and its accompanying dependencies.

The zoom issue also happens with the example above using `Tab`:
![4](https://user-images.githubusercontent.com/55868530/151509412-bd1037da-d6ff-4128-b375-6df840b014e9.gif)

**Comment by martinRenou** [comment]
This should be fixed in the latest release, which bqplot version are you using?

> I am using the beta release of ipywidgets 

This might be the reason for it to not work. Bqplot has not been updated yet for ipywidgets 8.

**Comment by samwelborn** [comment]
Using v0.12.32 of bqplot. I figured as much, just reporting in case you all didn't know about it. That, along with [this issue ](https://github.com/jupyter/jupyter-sphinx/issues/192) are the only ones I have noticed in using it despite 0.12.32 not fitting into the requirements of ipywidgets 8.

**Comment by samwelborn** [comment]
@martinRenou Do you have a rough estimate on when bqplot will be updated for ipywidgets 8? Just need to take this into consideration before rolling back/reconfiguring my gui.

**Comment by samwelborn** [comment]
Following up - I downgraded to the latest release of ipywidgets (7.6.5) and the `BrushSelector` problem still exists. 

It seems to only happen when the bqplot figures are in nested containers. My setup/workflow is as follows:
- 5 `Tab`s
- Each tab has several `Accordion`s
- The GUI opens on the first Tab. `BrushSelector` works inside of the Accordions on that tab. 
- I go to another Tab (any of the initially unopened ones), and the `BrushSelector` does not work inside of the accordions on that page.
- When I display what is contained inside of the Tabs (collections of Accordions, Boxes, bqplot figures, etc) in the same notebook, the `BrushSelector` works well.

**Comment by samwelborn** [comment]
Workaround: use an `Output` widget, and each time you select a `Tab` or `Accordion`, redraw it.

Here is my function:
```python
def create_dashboard():
    
    # creates stuff that sits inside Tabs (i.e. Accordions)
    file_import = Import_SSRL62() 
    center = Center(file_import) 
    align = Align(file_import, center)
    recon = Recon(file_import, center)
    dataexplorer = DataExplorerTab(align, recon)

    dashboard_tabs = [
        file_import.tab,
        center.tab,
        align.tab,
        recon.tab,
        dataexplorer.tab,
        file_import.log_handler.out,
    ]

    dashboard_titles = [
        "Import",
        "Center",
        "Align",
        "Reconstruct",
        "Data Explorer",
        "Log",
    ]

    dashboard = Tab(titles=dashboard_titles)
    dashboard.children = dashboard_tabs

    # workaround for nested bqplot issue
    def update_dashboard(change):
        dashboard.children = dashboard_tabs
        with dashboard_output:
            dashboard_output.clear_output(wait=True)
            display(dashboard)

    dashboard.observe(update_dashboard, names="selected_index")
    dashboard_output = Output()

    return (dashboard_output, file_import, center, align, recon, dataexplorer)

```
